### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by eidorb2** [eidorb/scorage#1]
1) save scoring like the names get saved. use a "reset" button to reset scores

2) add running total of bids

3) add running total of hands gotten (to check what was written down = number hands that round)

**Comment by eidorb** [comment]
Hi @eidorb2,

We at eidorb take your feedback very seriously. We will dedicate a team to investigate your request.

**Comment by eidorb** [comment]
All features requests implemented.

**Comment by eidorb2** [comment]
Fantastic work eidorb! I'll give it a real life trial tomorrow!
